// Jackson Coxson - Bindings to idevice - https://github.com/jkcoxson/idevice
// This file only wraps the C bindings for C++, the C bindings still must be
// generated.
// ``cargo build --release``

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "idevice.h" // this file is generated by bindgen

#ifdef __cplusplus
}
#endif
